version: '3.5'

services:
  chatgpt-clone:
    image: chatgpt-clone
    container_name: chatgpt-clone
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1338:1338"
